### ISSUE TITLE
Response : 

### ISSUE THREAD

**Issue by d3vilsn0w** [SchwarzwaldFalke/PokemonGO-SharedMap#1]
2016-08-14T14:52:16+00:00 NOTICE (5): Got CLOSE frame.

What is that suppose to mean?

**Comment by SchwarzwaldFalke** [comment]
It means the web socket got the CLOSE frame:
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#Closing_the_connection

In my example implementation this happens after each request:
https://github.com/SchwarzwaldFalke/PokemonGO-SharedMap/blob/master/src/Application.php#L85

Sometimes the connections gets closed without an anwser (timeout, server busy?, implementation error?).
